apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile-backend
  template:
    metadata:
      labels:
        app: seafile-backend
    spec:
      initContainers:  
        - name: set-ownership  
          image: busybox  
          command: ['sh', '-c', 'chown -R root:root /shared']  
          volumeMounts:  
          - name: seafile-data  
            mountPath: /shared
      containers:
        - name: seafile-backend
          image: {{ include "seafile.image" . }}
          env:
            - name: CLUSTER_INIT_MODE
              value: {{ .Values.seafile.initMode | quote}}
            - name: CLUSTER_SERVER
              value: "true"
            - name: CLUSTER_MODE
              value: "backend"
            - name: CACHE_PROVIDER
              value: "memcached"

            # common env
            {{- $overrideEnv := .Values.seafile.env -}}
            {{- $initMode := .Values.seafile.initMode -}}
            {{- range .Values.seafile.presetEnv }}
            - name: {{ .name }}
              {{- $valueFromEnv := (index $overrideEnv .name | default "") -}}
              {{- if and ($valueFromEnv) (not (eq $valueFromEnv "<required>")) }}
              value: {{ $valueFromEnv | quote }}
              {{- else if .value }}
              value: {{ .value | quote }}
              {{- else if or (.allowEmpty) (and (not $initMode) (.initValue)) }}
              value: ""
              {{- else }}
              {{- fail (printf "%s is not specified and is not allowed to be empty" .name) -}}
              {{- end }}
            {{- end }}

            # common secret
            {{- $overrideSecretMap := .Values.seafile.secretsMap -}}
            {{- range .Values.seafile.presetSecretsMap }}
            {{- $secretDetails := (index $overrideSecretMap .name | default (dict "secret" .secret "key" .key)) }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretDetails.secret | default .secret }}
                  key: {{ $secretDetails.key | default .key }}
            {{- end }}

            # extra envs
            {{- if .Values.seafile.extraEnv.backend }}
            {{- toYaml .Values.seafile.extraEnv.backend | nindent 12 }}
            {{- end }}

          volumeMounts:
            - name: seafile-data
              mountPath: /shared
            {{- range .Values.seafile.extraVolumes.backend }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              {{- if .readOnly }}
              readOnly: {{ .readOnly }}
              {{- end }}
            {{- end }}
          resources: {{- toYaml .Values.seafile.extraResources.backend | nindent 12 }}
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data
        {{- range .Values.seafile.extraVolumes.backend }}
        - name: {{ .name }}
          {{- toYaml .volumeInfo | nindent 10 }}
        {{- end }}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred